name: CI prod
on:
  push:
    branches:
      - main

  # workflow_dispatch = bouton dans github action
  workflow_dispatch:

# liste des jobs à exécuter
jobs:

  notify-server:
    runs-on: ubuntu-latest
    environment: stage
    steps:
    - name: Notify VPS
      run: |
        curl -X GET https://ops.032025-bleu-1.wns.wilders.dev/hooks/update-prod

