name: Docker test, build & image (PROD) #test for prod and stage
on:
  pull_request:
    branches:
      - dev-to-test-cd-ci-docker

jobs: 
  ci-cd-test-and-push:
    name: Docker push image on DockerHub for CI/CD
    runs-on: ubuntu-latest
    
    steps:
    #1. Checkout source code
    - name: Checkout source code
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    
    #2. Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    #3. Cache Docker Layers
    - name: Cache Docker Layers
      uses: actions/cache@v4
      with: 
        path: /tmp/.buildx-cache
        key: ${{ runner.os}}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os}}-buildx-

    #4. Cache npm dependencies
    - name: Cache npm dependencies
      uses: actions/cache@v4 
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.js') }}
        restore-keys: ${{ runner.os }}-npm-

    #5. Extract metadata
    - name: Extract metadata
      id: test
      run: |
        echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

    #6. Build all services with Docker Compose
    - name: Build all services with Docker Compose
      run: docker compose -f compose.prod.yaml build
      env:
        DB_PASSWORD: ${{ secrets.DOCKERHUB_TEST_DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DOCKERHUB_TEST_DB_DATABASE }}
        DB_USER: ${{ secrets.DOCKERHUB_TEST_DB_USER }}
        DB_HOST: ${{ secrets.DOCKERHUB_TEST_DB_HOST }}
        JWT_SECRET: ${{ secrets.DOCKERHUB_TEST_JWT_SECRET }}
        GATEWAY_PORT: ${{ secrets.GATEWAY_PORT }}

    #7. Start all services for tests
    - name: Start all services
      run: docker compose -f compose.prod.yaml up -d
      env:
        DB_PASSWORD: ${{ secrets.DOCKERHUB_TEST_DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DOCKERHUB_TEST_DB_DATABASE }}
        DB_USER: ${{ secrets.DOCKERHUB_TEST_DB_USER }}
        DB_HOST: ${{ secrets.DOCKERHUB_TEST_DB_HOST }}
        JWT_SECRET: ${{ secrets.DOCKERHUB_TEST_JWT_SECRET }}
        GATEWAY_PORT: ${{ secrets.GATEWAY_PORT }}

    #9. Print logs for all containers on failure
    - name: Print database logs on failure
      if: failure()
      run: docker logs database || true

    - name: Print backend logs on failure
      if: failure()
      run: docker logs backend-prod || true

    - name: Print frontend logs on failure
      if: failure()
      run: docker logs frontend-prod || true

    # 10. Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 11. Build and push prod image
    - name: Build and push production image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: compose.prod.yaml
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
        cache-from: type=local,src=/tmp/.buildx-cache