name: Docker test 
on:
  pull_request:
    branches:
      - develop

jobs: 
  docker-build-dev-test:
    name: Build test and push Docker image
    runs-on: ubuntu-latest
    
    steps:
    #1. Checkout source code
    - name: Checkout source code
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    
    #2. Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    #3. Cache Docker Layers
    - name: Cache Docker Layers
      uses: actions/cache@v4
      with: 
        path: /tmp/.buildx-cache
        key: ${{ runner.os}}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os}}-buildx-

    #4. Cache npm dependencies
    - name: Cache npm dependencies
      uses: actions/cache@v4 
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.js') }}
        restore-keys: ${{ runner.os }}-npm-

    #5. Extract metadata
    - name: Extract metadata
      id: meta
      run: |
        echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT
        echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

    #6. Build all services with Docker Compose
    - name: Build all services with Docker Compose
      run: docker compose -f compose.test.dev.yaml build

    #7. Start all services for tests
    - name: Start all services for tests
      run: docker compose -f compose.test.dev.yaml up -d

    #8. Run vitest tests and generate report (in backend-dev)
    - name: Run vitest tests and generate report
      run: |
        docker exec backend-dev sh -c "npm ci && npx vitest run --reporter=verbose"
      env:
        CI: true
        NODE_ENV: test
      timeout-minutes: 10

    #8. Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    #9. Build and push dev image 
    - name: Build and push docker dev image
      uses: docker/build-push-action@v6 
      with: 
        context: . 
        file: compose.test.dev.yaml
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
        cache-from: type=local,src=/tmp/.buildx-cache